spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: 'false'
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations: file:src/main/resources/static/, classpath:/static/
      cache:
        period: 0

  devtools:
    restart:
      enabled: 'true'
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
        - src/main/java/